- LICENSE
- README.md
This is in prep for release.
* Align README w/std-readme spec
* Clean up / reword README a bit
* Add a LICENSE file
> Adjust readme to std-readme spec

- .travis.yml
- lib/test/fundAddress.js
- lib/test/getDAPISeeds.js
- lib/test/getInputsByAddress.js
- lib/waitForBlocks.js
- package-lock.json
- package.json
- test/functional/core/broadcastTransaction.spec.js
- test/functional/core/getAddressSummary.spec.js
- test/functional/core/getBlock.spec.js
- test/functional/core/getBlockHash.spec.js
- test/functional/core/getStatus.spec.js
- test/functional/core/getTransaction.spec.js
- test/functional/platform/DataContract.spec.js
- test/functional/platform/Document.spec.js
- test/functional/platform/Identity.spec.js
fix: old tests for new dependencies
Need tests for document $createdAt and $updatedAt timestamps
Added test cases for document timestamps:
* fetch created document by time range
* update the created document
* fail to update document with timestamp in violated time frame 
* fail to create a new document with timestamp in violated time frame
Tests
None
> feat: add document timestamp tests

- package-lock.json
- package.json
- test/e2e/contacts.spec.js
Update `dpp` to `0.14.0-dev.4`
Update `dpp` to `0.14.0-dev.4`. Updated `contracts` contract.
Tests.
None.
> feat: update dpp to 0.14.0-dev.4

- package-lock.json
- package.json
Updated version to `0.14.0-dev.3`
Updated version to `0.14.0-dev.3`
Tests.
None.
> chore: update version to 0.14.0-dev.3

- package-lock.json
- package.json
update `dash` to `3.14.0-dev.4`
update `dash` to `3.14.0-dev.4`
Tests.
- `addresses` were renamed to `dapiAddresses`
> feat: update `dash` to 3.14.0-dev.4

- README.md
Updating `README` to be more comprehensive.
Updated `README` to be more comprehensive.
None.
> feat: slightly more comprehensive README

- package-lock.json
- package.json
Need to update DashJs
DashJs was updated to 3.15.0-dev.1
Unit tests
None
> feat: update dash to 3.15.0-dev.1

- package-lock.json
- package.json
- test/functional/platform/Identity.spec.js
Added new topup identity test
Tests
None
> feat: new topup identity test

- Dockerfile
We need to have an opportunity to install node modules from git on docker start
Changed Dockerfile
Manually
None
> feat: support for installation node module from git on docker start

- .travis.yml
To have more consistent testing we need to have an opportunity to use unmerged dapi and drive code during tests running
Changed Travis script
Travis builds
None
> build: install DAPI and Drive from branch during Travis build

- README.md
Brings readme into [standard-readme](https://github.com/RichardLitt/standard-readme) compliance
Minor formatting/link updates. Badges added.
N/A
N/A
> docs: readme standard updates

- package-lock.json
- package.json
- test/functional/platform/Document.spec.js
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
> chore: bump version to 0.15.0-dev.4

- package-lock.json
- package.json
Updated `dashjs` to latest dev release
Updated `dashjs` to latest dev release
> feat: update `dashjs` to 3.15.0-dev.3

- package-lock.json
- package.json
To make a new pre-release we need to bump version
Bumped version
Unit tests
None
> chore: bump version to 0.15.0-dev.5

- test/functional/core/subscribeToTransactionsWIthProofs.spec.js
We're removing pending functional tests as we keep them in `dapi`
Removed pending tests
> feat: remove pending `subscribeToTransactionsWithProofs` functional tests

- lib/test/createFaucetClient.js
- test/e2e/wallet.spec.js
Skipped test that otherwise would prevent deploying 0.15
Skipped 3 wallet tests that depend on the edge case in the tx stream
Run npm test
None
> chore: skip some wallet tests

- lib/test/bootstrap.js
- package-lock.json
- package.json
- test/e2e/contacts.spec.js
- test/e2e/dpns.spec.js
- test/functional/platform/Document.spec.js
- test/functional/platform/Identity.spec.js
dpns-contract, dpp, grpc-common, wallet-lib, dash were updated to the latest dev versions. Tests were updated to work with updated libraries.
Tests
> chore: update to SDK 0.16

- .travis.yml
> build: use GitHub token for API requests

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.16
- Updated changelog
- Updated dependencies
- Bumped version 
None
None
> chore(release): update changelog and bump version to `0.16.0`

- package-lock.json
- package.json
Release 0.17.0-dev.1
Bump version to 0.17.0-dev.1
With tests
None
> chore(release): bump version to 0.17.0-dev.1

- test/functional/core/getTransaction.spec.js
- test/functional/platform/Identity.spec.js
> fix: invalid assertions in `Identity` functional test

- package-lock.json
- package.json
> chore: bump version to `0.17.0-dev.3`

- package-lock.json
- package.json
- test/functional/platform/Identity.spec.js
Added test for identity funding double spends
Add two test cases that reuse the same transaction that was already used 
Run the tests
None
> feat: identity funding double-spend tests

- package-lock.json
- package.json
>  chore(release): bump version to `0.17.0-dev.4`

- package-lock.json
- package.json
bump version to 0.17.0-dev.5
bump version to 0.17.0-dev.5
> chore: bump version to 0.17.0-dev.5

- test/functional/platform/Identity.spec.js
Run test suite against regtest and palinka networks
No
> feat: make test works without fallback

- .travis.yml
Removed after_script from travis yaml
No
> chore: remove after script from travis

- test/functional/platform/DataContract.spec.js
- test/functional/platform/Document.spec.js
- test/functional/platform/Identity.spec.js
Fixed Identity tests against testnet
> fix: Identity tests against testnet

- package-lock.json
- package.json
> chore: update sdk version to 3.18.0-dev.1

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.18.0
- Update changelog
- Bump version to 0.18.0
None
None
> chore(release): update changelog and bump version 0.18.0

- bin/test.sh
Bash script could not run mocha in github actions
Fixed test.sh
Through github actions
No
> fix: bash script could not run mocha in github actions

- package-lock.json
- package.json
Not patched version of protobuf.js is installed
- updated grpc-common with specified patched protobuf.js
With tests
None
> fix: not patched version of protobufjs is used

- package-lock.json
- package.json
Bump version to 0.19.0-dev.4
No
> chore: bump version to 0.19.0-dev.4

- test/functional/platform/Identity.spec.js
Identity Chainlock tests are failing against Palinka
fixed Identity Chainlock tests
Tests
No
> fix: Identity Chainlock tests are failing against Palinka

- package-lock.json
- package.json
Updated `wallet-lib` version
- updated `wallet-lib`
- `npm dedupe`
None.
> fix: invalid `wallet-lib` version was set

- test/e2e/dpns.spec.js
- test/functional/platform/Document.spec.js
- test/functional/platform/Identity.spec.js
When tests are failing, developers see only the error code, not the error message
Changed the order of error checks from code, message to message, code, so developers can see the actual error message
Hasn't been
None
> feat: change an order of error check to provide better and faster debug info

- .github/workflows/test_and_release.yml
CI for this repo could benefit from layer caching
- Enable layer caching
In CI
> ci: use buildkit cache

- .mocharc.yml
- test/functional/platform/Identity.spec.js
Chainlock tests are back!
- updated and re-enabled chainlock test cases
Local setup and testing
None.
> feat: return chainlock test cases 

- .github/workflows/.env
- test/functional/platform/Document.spec.js
Document proof format wasn't tested
Add a simple test case to ensure document proof has a correct format
Run the test 
None
> feat: check the proof format for waitForStateTrasitionResult

- .github/workflows/.env
> ci: remove env branches

- .github/workflows/.env
- CHANGELOG.md
Latest corrections for a release
- updated change log
- workflow setup
> chore: update workflow and changelog for a release

- .github/workflows/.env
- package-lock.json
- package.json
- test/functional/platform/Document.spec.js
> chore: bump version to 0.21.0-dev.1

- .github/workflows/.env
- bin/test.sh
- package-lock.json
- package.json
The test is failing due to comparing instances from different versions of dependecies:
```
1) Core
getTransaction
should throw NotFound error if transaction was not found:
AssertionError: expected [NotFoundError: Transaction 0000000000000000000000000000000000000000000000000000000000000000 is not found] to be an instance of NotFoundError
at Context.<anonymous> (test/functional/core/getTransaction.spec.js:45:28)
```
It happens when the `--npm-install` option is passed. 
- Run `npm dedupe` after `npm install` when `--npm-install` option is passed.
With CI
None
> fix: expected `NotFoundError` to be an instance of `NotFoundError`

- package-lock.json
- package.json
- test/functional/platform/Identity.spec.js
> chore: update dash sdk

- package-lock.json
> chore: dedupe protobuf

- package-lock.json
- package.json
Test suite was failing against schnapps with inconsistent errors, some mentioning `wallet-lib`
- Update `wallet-lib`
Tested on schnapps, result is less errors and more consistent reproduction of errors
> chore: update wallet-lib

- .github/workflows/.env
- package-lock.json
- package.json
> chore: bump version to 0.21.0-dev.4

- package-lock.json
- package.json
Bump version for release
Bump version to 0.21.0-dev.5
> chore: bump version to v0.21-dev.5

- bin/test.sh
Some `echo` statements were left over after debugging in GitHub Actions, making the command output confusing.
Remove unnecessary debug output
In CI
None
> chore: clean up unnecessary debug output

- test/functional/platform/waitForStateTransitionResult.spec.js
Add an additional test to check that `waitForStateTransitionResult` returns a correct proof
- add a test to parse `waitForStateTransitionResult` proof
Run the newly added test
None
> feat: add a test for parsing waitForStateTransitionResult proof
